baseURL = "https://moveitraleigh.com/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Move It Raleigh"
disableKinds = ["taxonomyTerm"]

[blackfriday]
  hrefTargetBlank = true

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":fileModTime", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[params]
  description = "Move It Raleigh is a community-based campaign to encourage residents in the Triangle area to get out and move, with a specific focus on the performing arts."
  images = ["/img/banner.jpg"]
  title = "Move It Raleigh"
  header_image = "img/mir-full.png"

 [taxonomies]
   participant = "participants"
   sponsor = "sponsors"

# [taxonomies]
#   series = "series"
#   event = "events"
#   tag = "tags"
#   category = "categories"

[markup.goldmark.renderer]
  unsafe= true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Who We Are"
    title = "Who We Are"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "benefit-concert"
    name = "Benefit Concert"
    url = "/events/3rd-annual-benefit/"
    weight = 40

  [[menu.main]]
    identifier = "community-opportunities"
    name = "Community Opportunities"
    url = "/events/raleigh-moves-together/"
    weight = 50

  [[menu.main]]
    identifier = "community-dance"
    parent = "community-opportunities"
    name = "Past Opportunities"
    url = "/events/community-dance/"
    weight = 50

  [[menu.main]]
    identifier = "auction"
    name = "Silent Auction"
    url = "/events/3rd-annual-benefit/auction/"
    weight = 70

 [[menu.main]]
   identifier = "donate"
   name = "Donate"
   url = "/donate/"
   weight = 80

 [[menu.main]]
   identifier = "sponsor"
   name = "Sponsorship"
   title = "sponsorship"
   url = "/sponsor/"
   weight = 90

 [[menu.main]]
   identifier = "advertise"
   name = "Ad"
   url = "/events/3rd-annual-benefit/advertise/"
   weight = 95

 [[menu.main]]
   identifier = "connect"
   name = "Join the MOVEment"
   title = "Connect With Us"
   url = "/connect/"
   weight = 100
